# syntax=docker/dockerfile:1

FROM quay.io/quarkus/ubi9-quarkus-micro-image:2.0
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work

COPY --chown=1001:root --chmod=0755 target/mec-backend-1.0.0-SNAPSHOT-runner /work/application

EXPOSE 8080
USER 1001

ENV QUARKUS_PROFILE=prod

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
