quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_URL}

quarkus.redis.hosts=${REDIS_URL}

mp.jwt.verify.publickey.location=${JWT_PUBLIC_KEY_LOCATION:classpath:keys/publicKey.pem}
smallrye.jwt.sign.key.location=${JWT_SIGN_KEY_LOCATION:classpath:keys/privateKey.pem}

quarkus.swagger-ui.always-include=false
quarkus.http.auth.permission.public.paths=/api/auth/login,/api/auth/refresh,/api/auth/logout,/api/auth/verificar-primeiro-acesso,/api/auth/primeiro-acesso,/api/localidades/estados/*

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=${CORS_ORIGINS:https://localhost}
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
quarkus.http.cors.headers=accept,authorization,content-type,origin,x-requested-with,x-csrf-token
quarkus.http.cors.exposed-headers=authorization
quarkus.http.cors.access-control-allow-credentials=true

vortex.auth.cookie.secure=true
vortex.auth.cookie.same-site=None

vortex.rate-limit.trust-proxy=true
vortex.auth.csrf.enabled=true
vortex.auth.csrf.cookie-path=/
