ALTER TABLE clientes ADD COLUMN IF NOT EXISTS tipo_pessoa VARCHAR(20) NOT NULL DEFAULT 'PESSOA_FISICA';
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS cnpj VARCHAR(18);
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS razao_social VARCHAR(150);
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS nome_fantasia VARCHAR(150);

ALTER TABLE clientes DROP CONSTRAINT IF EXISTS uk_clientes_cnpj;
ALTER TABLE clientes ADD CONSTRAINT uk_clientes_cnpj UNIQUE (cnpj);
