CREATE TABLE IF NOT EXISTS enderecos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cep VARCHAR(9) NOT NULL,
    logradouro VARCHAR(255),
    complemento VARCHAR(255),
    numero VARCHAR(20),
    bairro VARCHAR(150),
    cidade VARCHAR(150),
    uf VARCHAR(2),
    estado VARCHAR(100),
    ibge VARCHAR(10),
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL,
    usuario_inclusao_id BIGINT,
    usuario_alteracao_id BIGINT
);

CREATE TABLE IF NOT EXISTS clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    tipo_pessoa VARCHAR(20) NOT NULL DEFAULT 'PESSOA_FISICA',
    endereco_id BIGINT,
    cpf VARCHAR(14),
    cnpj VARCHAR(18),
    razao_social VARCHAR(150),
    nome_fantasia VARCHAR(150),
    telefone VARCHAR(20),
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL,
    usuario_inclusao_id BIGINT,
    usuario_alteracao_id BIGINT,
    CONSTRAINT uk_clientes_cpf UNIQUE (cpf),
    CONSTRAINT uk_clientes_cnpj UNIQUE (cnpj),
    CONSTRAINT uk_clientes_endereco_id UNIQUE (endereco_id),
    CONSTRAINT fk_clientes_endereco FOREIGN KEY (endereco_id) REFERENCES enderecos (id)
);

CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(150) NOT NULL,
    senha VARCHAR(255),
    nome VARCHAR(150) NOT NULL,
    perfil VARCHAR(20) NOT NULL,
    cliente_id BIGINT,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    deve_definir_senha BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL,
    usuario_inclusao_id BIGINT,
    usuario_alteracao_id BIGINT,
    CONSTRAINT uk_usuarios_email UNIQUE (email),
    CONSTRAINT uk_usuarios_cliente_id UNIQUE (cliente_id),
    CONSTRAINT fk_usuarios_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (id)
);

MERGE INTO usuarios (email, senha, nome, perfil, ativo, deve_definir_senha, criado_em, atualizado_em)
KEY (email)
VALUES (
    'admin@vortex.com',
    '$2a$10$uVthyddDgHbLYpzdkg6uV.i.SITKooF.QgWjsjtczMKNOa620SsYi',
    'Administrador',
    'ADMIN',
    TRUE,
    FALSE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL,
    usuario_id BIGINT NOT NULL,
    expira_em TIMESTAMP NOT NULL,
    revogado BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em TIMESTAMP NOT NULL,
    CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_usuario_revogado ON refresh_tokens (usuario_id, revogado);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_expira_em ON refresh_tokens (expira_em);

CREATE TABLE IF NOT EXISTS veiculos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa VARCHAR(10) NOT NULL,
    marca VARCHAR(80) NOT NULL,
    modelo VARCHAR(120) NOT NULL,
    ano_fabricacao INTEGER NOT NULL,
    motor VARCHAR(30),
    combustivel VARCHAR(30),
    km_atual INTEGER,
    cliente_id BIGINT NOT NULL,
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL,
    usuario_inclusao_id BIGINT,
    usuario_alteracao_id BIGINT,
    CONSTRAINT uk_veiculos_placa UNIQUE (placa),
    CONSTRAINT fk_veiculos_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (id)
);

CREATE TABLE IF NOT EXISTS ordens_servico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    veiculo_id BIGINT NOT NULL,
    tecnico_id BIGINT NOT NULL,
    data DATE NOT NULL,
    hora TIME NOT NULL,
    km_entrada INTEGER,
    km_saida INTEGER,
    custo_servicos_terceirizados DECIMAL(12, 2) NOT NULL DEFAULT 0,
    descricao_servicos_terceirizados VARCHAR(500),
    custo_pecas DECIMAL(12, 2) NOT NULL DEFAULT 0,
    custo_mao_de_obra DECIMAL(12, 2) NOT NULL DEFAULT 0,
    descricao_mao_de_obra VARCHAR(500),
    preco_total DECIMAL(12, 2) NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'ORCAMENTO',
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL,
    usuario_inclusao_id BIGINT,
    usuario_alteracao_id BIGINT,
    CONSTRAINT fk_ordens_servico_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (id),
    CONSTRAINT fk_ordens_servico_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos (id),
    CONSTRAINT fk_ordens_servico_tecnico FOREIGN KEY (tecnico_id) REFERENCES usuarios (id)
);

CREATE TABLE IF NOT EXISTS ordens_servico_itens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ordem_servico_id BIGINT NOT NULL,
    descricao VARCHAR(255) NOT NULL,
    quantidade DECIMAL(10, 2) NOT NULL DEFAULT 1,
    valor_unitario DECIMAL(12, 2) NOT NULL DEFAULT 0,
    tipo VARCHAR(20) NOT NULL,
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL,
    usuario_inclusao_id BIGINT,
    usuario_alteracao_id BIGINT,
    CONSTRAINT fk_ordens_servico_itens_os FOREIGN KEY (ordem_servico_id) REFERENCES ordens_servico (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ordens_servico_status_historico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ordem_servico_id BIGINT NOT NULL,
    status_anterior VARCHAR(30),
    status_novo VARCHAR(30) NOT NULL,
    usuario_id BIGINT,
    origem VARCHAR(30) NOT NULL DEFAULT 'SISTEMA',
    observacao VARCHAR(500),
    criado_em TIMESTAMP NOT NULL,
    CONSTRAINT fk_os_status_hist_ordem
        FOREIGN KEY (ordem_servico_id) REFERENCES ordens_servico (id) ON DELETE CASCADE,
    CONSTRAINT fk_os_status_hist_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT chk_os_status_hist_origem
        CHECK (origem IN ('CLIENTE', 'TECNICO', 'ADMIN', 'SISTEMA'))
);

MERGE INTO usuarios (email, senha, nome, perfil, ativo, deve_definir_senha, criado_em, atualizado_em)
KEY (email)
VALUES (
    'tecnico@vortex.com',
    '$2a$10$uVthyddDgHbLYpzdkg6uV.i.SITKooF.QgWjsjtczMKNOa620SsYi',
    'Técnico Teste',
    'TECNICO',
    TRUE,
    FALSE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS municipios (
    id INTEGER PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    uf VARCHAR(2) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_municipios_uf ON municipios (uf);

MERGE INTO municipios (id, nome, uf) KEY (id) VALUES (3106200, 'Belo Horizonte', 'MG');
MERGE INTO municipios (id, nome, uf) KEY (id) VALUES (3136702, 'Juiz de Fora', 'MG');
MERGE INTO municipios (id, nome, uf) KEY (id) VALUES (3170206, 'Uberlândia', 'MG');
